---
title: "Homework 4: Namit Shrivastava"
format: pdf
editor: visual
---

## Problem Statement

Your client is a retail banking institution. Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. 

The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing and digital marketing. Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. 

Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call. You are provided with the client data such as: age of the client, their job type, their marital status, etc. Along with the client data, you are also provided with the information of the call such as the duration of the call, day and month of the call, etc. Given this information, your task is to predict if the client will subscribe to term deposit.

## Data Dictionary
$$

```{=tex}
\begin{center}
\begin{tabular}{|l|p{10cm}|}
\hline
\textbf{Variable} & \textbf{Definition} \\
\hline
ID & Unique client ID \\
\hline
age & Age of the client \\
\hline
job & Type of job \\
\hline
marital & Marital status of the client \\
\hline
education & Education level \\
\hline
default & Credit in default \\
\hline
balance & Average yearly balance \\
\hline
housing & Housing loan \\
\hline
loan & Personal loan \\
\hline
contact & Type of communication \\
\hline
month & Contact month \\
\hline
day & Day of week of contact \\
\hline
duration & Contact duration \\
\hline
campaign & Number of contacts performed during this campaign to the client \\
\hline
pdays & Number of days that passed by after the client was last contacted \\
\hline
previous & Number of contacts performed before this campaign \\
\hline
poutcome & Outcome of the previous marketing campaign \\
\hline
subscribed & Has the client subscribed a term deposit? (target variable) \\
\hline
\end{tabular}
\end{center}
$$

## 1a. [10 points] Create an empirical logit plot with the response variable (y) subscribed by the predictor variable (x) age. You may want to convert subscribed to a numeric variable first.

The empirical logit is calculated using the formula:

$$
\text{empirical logit} = \ln\left(\frac{p + \frac{1}{2n}}{1 - p + \frac{1}{2n}}\right)
$$

where:
- $p$ is the proportion of successes in each group
- $n$ is the number of observations in each group
```{r}
# Loading the required libraries
library(dplyr)
library(ggplot2)

# Reading the data
deposit_data <- read.csv("deposit-1.csv")

# Converting subscribed to numeric
deposit_data$subscribed_num <- ifelse(deposit_data$subscribed == "yes", 1, 0)

# Calculating empirical logits by age
empirical_logits <- deposit_data %>%
  group_by(age) %>%
  summarize(
    n = n(),
    successes = sum(subscribed_num),
    p = successes/n,
    emp_logit = log((p + 1/(2*n))/(1 - p + 1/(2*n)))
  )

# Creating the empirical logit plot
ggplot(empirical_logits, aes(x = age, y = emp_logit)) +
  geom_point() +
  geom_smooth(method = "loess", se = TRUE) +
  labs(
    title = "Empirical Logit Plot",
    x = "Age",
    y = "Empirical Logit",
    caption = "Note: Blue line shows LOESS smooth with 95% confidence interval"
  ) +
  theme_minimal()

# Displaying first few rows of calculations
knitr::kable(
  head(empirical_logits),
  caption = "Sample of Empirical Logit Calculations",
  digits = 4
)
```