```{r}
data <- read.table("/Users/namomac/Downloads/spacshu.dat")
names(data) <- c("temp", "damage")

# Create temperature categories
data$temp_cat <- cut(data$temp, 
                     breaks = c(0, 60, 65, 70, 75, Inf),
                     labels = c("<=60", "61-65", "66-70", "71-75", ">=75"))

data
```
```{r}
# 1. Calculate cell probabilities
cell_probs <- aggregate(damage ~ temp_cat, data = data, 
                       FUN = function(x) c(mean(x), length(x)))
cell_probs <- do.call(data.frame, cell_probs)
names(cell_probs) <- c("temp_cat", "probability", "count")
cell_probs
```
> cell_probs
  temp_cat probability count
1     <=60  0.22222222    18
2    61-65  0.16666667     6
3    66-70  0.03333333    60
4    71-75  0.08333333    24
5     >=75  0.00000000    30

```{r}
cell_counts <- table(data)
total_observations <- sum(cell_counts)
cell_probabilities <- cell_counts / total_observations

cell_probabilities
```

```{r}
# Create categorical variable for temperature ranges
data$TempCat <- cut(data$Temp, breaks=c(-Inf, 55, 60, 65, 70, 75, Inf), labels=c("<=55", "56-60", "61-65", "66-70", "71-75", ">=75"))

# Calculate cell probabilities
cell_counts <- table(data$Temp, data$damage, data$TempCat)
total_observations <- sum(cell_counts)
cell_probabilities <- cell_counts / total_observations

# Convert the table to a data frame for easier viewing
simplified_table <- as.data.frame(cell_probabilities)

# Print the simplified table
print(simplified_table)
```

```{r}
orings2 <- read.table("/Users/namomac/Downloads/spacshu.dat", header = FALSE)
colnames(orings2) <- c("temp", "damage")

# Categorize temperatures
orings2$temp.grp <- NA
orings2$temp.grp[orings2$temp < 60] <- 55
orings2$temp.grp[orings2$temp >= 60 & orings2$temp < 65] <- 60
orings2$temp.grp[orings2$temp >= 65 & orings2$temp < 70] <- 65
orings2$temp.grp[orings2$temp >= 70 & orings2$temp < 75] <- 70
orings2$temp.grp[orings2$temp >= 75] <- 75

# Compute Relative Risk (RR)
lower_than_60 <- orings2[orings2$temp.grp == 55, ]
equal_or_higher_75 <- orings2[orings2$temp.grp == 75, ]

risk_lower_60 <- sum(lower_than_60$damage) / nrow(lower_than_60)
risk_higher_75 <- sum(equal_or_higher_75$damage) / nrow(equal_or_higher_75)

relative_risk <- risk_lower_60 / risk_higher_75

# Compute Odds Ratios (OR)
odds_lower_60 <- sum(lower_than_60$damage) / sum(lower_than_60$damage == 0)
odds_higher_75 <- sum(equal_or_higher_75$damage) / sum(equal_or_higher_75$damage == 0)

# Difference between Odds Ratios
difference_odds_ratios <- odds_higher_75 - odds_lower_60

# Print the results
cat("Relative Risk (Lower than 60 compared to Equal or higher than 75):", relative_risk, "\n")
cat("Odds Ratio of o-ring failure at Lower than 60 degrees:", odds_lower_60, "\n")
cat("Odds Ratio of o-ring failure at Equal or higher than 75 degrees:", odds_higher_75, "\n")
cat("Difference between Odds Ratios:", difference_odds_ratios, "\n")
```
```{r}
# 6. Fit logistic regression model
# Create dummy variables for temperature categories
# Create categorical variable for Temp
data$TempCat <- factor(data$Temp, levels = c(55, 60, 65, 70, 75))

# Fit logistic regression model
model <- glm(Damage ~ TempCat, data = data, family = binomial)

summary(model)
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)  
(Intercept)     -0.6931     0.8660  -0.800   0.4235  
temp_cat56-60   -0.9163     1.1619  -0.789   0.4303  
temp_cat61-65   -0.9163     1.3964  -0.656   0.5117  
temp_cat66-70   -2.6741     1.1257  -2.376   0.0175 *
temp_cat71-75   -1.7047     1.1382  -1.498   0.1342  
temp_cat>=75   -18.8729  1963.4054  -0.010   0.9923  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 66.540  on 137  degrees of freedom
Residual deviance: 55.164  on 132  degrees of freedom
AIC: 67.164

Number of Fisher Scoring iterations: 18









Relative Risk
```{r}
dead <- c(73, 2)    # Dead: Conc > 0, Conc = 0
alive <- c(47, 28)  # Alive: Conc > 0, Conc = 0

prospective_table <- matrix(c(dead, alive), nrow = 2, byrow = TRUE)
colnames(prospective_table) <- c("Conc > 0", "Conc = 0")
rownames(prospective_table) <- c("Dead", "Alive")

risk_conc_greater_0 <- prospective_table[1, 1] / (prospective_table[1, 1] + prospective_table[2, 1])
risk_conc_equal_0 <- prospective_table[1, 2] / (prospective_table[1, 2] + prospective_table[2, 2])
relative_risk <- risk_conc_greater_0 / risk_conc_equal_0

relative_risk
```

Odds ratio

```{r}
case <- c(73, 2)    # Cases: Conc > 0, Conc = 0
control <- c(47, 28)  # Controls: Conc > 0, Conc = 0

retrospective_table <- matrix(c(case, control), nrow = 2, byrow = TRUE)
colnames(retrospective_table) <- c("Conc > 0", "Conc = 0")
rownames(retrospective_table) <- c("Case", "Control")

odds_conc_greater_0 <- retrospective_table[1, 1] / retrospective_table[2, 1]
odds_conc_equal_0 <- retrospective_table[1, 2] / retrospective_table[2, 2]
odds_ratio <- odds_conc_greater_0 / odds_conc_equal_0

odds_ratio

```